INSERT INTO public.groups (id, value) VALUES (1, 'September №1');
INSERT INTO public.groups (id, value) VALUES (2, 'September №2');
INSERT INTO public.groups (id, value) VALUES (11, 'Number 1');
INSERT INTO public.groups (id, value) VALUES (12, 'Number 21');
INSERT INTO public.groups (id, value) VALUES (20, 'Number 221');
INSERT INTO public.groups (id, value) VALUES (26, 'Number 228');
INSERT INTO public.groups (id, value) VALUES (30, 'Number 229');
INSERT INTO public.groups (id, value) VALUES (32, 'Number 3330');
INSERT INTO public.groups (id, value) VALUES (33, 'Number 3333');
INSERT INTO public.groups (id, value) VALUES (34, 'HTML');
INSERT INTO public.groups (id, value) VALUES (35, 'HTML1');